[package]
name = "signalfs"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
axum = "0.6.18"
cid = "0.10.1"
serde = "1.0.163"
serde_json = "1.0.96"
tokio = { version = "1.28", features = ["full"] }
tower = "0.4.13"
tracing-subscriber = "0.3.17"
